import { format } from 'prettier';
import parserCss from 'prettier/parser-postcss';

import { Styles } from '../models/styles';
import { WriteCSSRule } from '../utils/css';
import { IBundleContext } from './compile';
import { ModuleMap } from './module-map';
import { normalizeCSS } from './normalize';

export class CompilerStyleSheet extends ModuleMap<Styles> {

  constructor(public readonly context: IBundleContext) { super(); }

  parser = 'css';

  renderModule(content: Styles, module: string): string { return WriteCSSRule(content, module); }

  wrap(renderedContent: string): string {
    return `
      /* Generated by ewibs: http://ewibs.app */
      ${renderedContent}
    `;
  }

  // TODO: This should probably not exist
  private unwrap(renderedContent: string): string {
    return renderedContent.replace('/* Generated by ewibs: http://ewibs.app */', '');
  }

  override renderGlobal(): string {
    const base = this.wrap(`
      ${this.renderModule(this.context.assembly.settings.globalStyle.styles, 'body, html')}
      ${this.unwrap(super.renderGlobal())}
    `);
    if (this.context.assembly.settings.globalStyle.normalize) {
      return format(`
        ${normalizeCSS}
        ${base}
      `, { parser: this.parser, plugins: [parserCss] });
    }
    return base;
  }

}